/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as AppIndustryRouteImport } from './routes/_app.industry'
import { Route as onboardingUploadRouteImport } from './routes/(onboarding)/upload'
import { Route as onboardingProcessingRouteImport } from './routes/(onboarding)/processing'
import { Route as onboardingOnboardingRouteImport } from './routes/(onboarding)/onboarding'
import { Route as onboardingConsentRouteImport } from './routes/(onboarding)/consent'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAcceptInviteIndexRouteImport } from './routes/(auth)/accept-invite.index'
import { Route as AppspotlightsSpotlightsRouteImport } from './routes/_app/(spotlights)/spotlights'
import { Route as AppspendingSpendingRouteImport } from './routes/_app/(spending)/spending'
import { Route as AppsettingsSettingsRouteImport } from './routes/_app/(settings)/settings'
import { Route as AppprofileWrappedRouteImport } from './routes/_app/(profile)/wrapped'
import { Route as AppprofileProfileRouteImport } from './routes/_app/(profile)/profile'
import { Route as AppdashboardHomeRouteImport } from './routes/_app/(dashboard)/home'
import { Route as AppcoachCoachRouteImport } from './routes/_app/(coach)/coach'
import { Route as AppagentsAgentsRouteImport } from './routes/_app/(agents)/agents'
import { Route as authAcceptInviteTokenRouteImport } from './routes/(auth)/accept-invite.$token'
import { Route as AppspotlightsSpotlightsIdRouteImport } from './routes/_app/(spotlights)/spotlights.$id'
import { Route as AppspendingSpendingCategoryRouteImport } from './routes/_app/(spending)/spending.$category'
import { Route as AppspotlightsSpotlightsIdApplyRouteImport } from './routes/_app/(spotlights)/spotlights.$id_.apply'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndustryRoute = AppIndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => AppRoute,
} as any)
const onboardingUploadRoute = onboardingUploadRouteImport.update({
  id: '/(onboarding)/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingProcessingRoute = onboardingProcessingRouteImport.update({
  id: '/(onboarding)/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingOnboardingRoute = onboardingOnboardingRouteImport.update({
  id: '/(onboarding)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingConsentRoute = onboardingConsentRouteImport.update({
  id: '/(onboarding)/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInviteIndexRoute = authAcceptInviteIndexRouteImport.update({
  id: '/(auth)/accept-invite/',
  path: '/accept-invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppspotlightsSpotlightsRoute = AppspotlightsSpotlightsRouteImport.update({
  id: '/(spotlights)/spotlights',
  path: '/spotlights',
  getParentRoute: () => AppRoute,
} as any)
const AppspendingSpendingRoute = AppspendingSpendingRouteImport.update({
  id: '/(spending)/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppsettingsSettingsRoute = AppsettingsSettingsRouteImport.update({
  id: '/(settings)/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppprofileWrappedRoute = AppprofileWrappedRouteImport.update({
  id: '/(profile)/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const AppprofileProfileRoute = AppprofileProfileRouteImport.update({
  id: '/(profile)/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppdashboardHomeRoute = AppdashboardHomeRouteImport.update({
  id: '/(dashboard)/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppcoachCoachRoute = AppcoachCoachRouteImport.update({
  id: '/(coach)/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppagentsAgentsRoute = AppagentsAgentsRouteImport.update({
  id: '/(agents)/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const authAcceptInviteTokenRoute = authAcceptInviteTokenRouteImport.update({
  id: '/(auth)/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppspotlightsSpotlightsIdRoute =
  AppspotlightsSpotlightsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppspotlightsSpotlightsRoute,
  } as any)
const AppspendingSpendingCategoryRoute =
  AppspendingSpendingCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AppspendingSpendingRoute,
  } as any)
const AppspotlightsSpotlightsIdApplyRoute =
  AppspotlightsSpotlightsIdApplyRouteImport.update({
    id: '/$id_/apply',
    path: '/$id/apply',
    getParentRoute: () => AppspotlightsSpotlightsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof landingIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/consent': typeof onboardingConsentRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/processing': typeof onboardingProcessingRoute
  '/upload': typeof onboardingUploadRoute
  '/industry': typeof AppIndustryRoute
  '/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/agents': typeof AppagentsAgentsRoute
  '/coach': typeof AppcoachCoachRoute
  '/home': typeof AppdashboardHomeRoute
  '/profile': typeof AppprofileProfileRoute
  '/wrapped': typeof AppprofileWrappedRoute
  '/settings': typeof AppsettingsSettingsRoute
  '/spending': typeof AppspendingSpendingRouteWithChildren
  '/spotlights': typeof AppspotlightsSpotlightsRouteWithChildren
  '/accept-invite/': typeof authAcceptInviteIndexRoute
  '/spending/$category': typeof AppspendingSpendingCategoryRoute
  '/spotlights/$id': typeof AppspotlightsSpotlightsIdRoute
  '/spotlights/$id/apply': typeof AppspotlightsSpotlightsIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof landingIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/consent': typeof onboardingConsentRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/processing': typeof onboardingProcessingRoute
  '/upload': typeof onboardingUploadRoute
  '/industry': typeof AppIndustryRoute
  '/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/agents': typeof AppagentsAgentsRoute
  '/coach': typeof AppcoachCoachRoute
  '/home': typeof AppdashboardHomeRoute
  '/profile': typeof AppprofileProfileRoute
  '/wrapped': typeof AppprofileWrappedRoute
  '/settings': typeof AppsettingsSettingsRoute
  '/spending': typeof AppspendingSpendingRouteWithChildren
  '/spotlights': typeof AppspotlightsSpotlightsRouteWithChildren
  '/accept-invite': typeof authAcceptInviteIndexRoute
  '/spending/$category': typeof AppspendingSpendingCategoryRoute
  '/spotlights/$id': typeof AppspotlightsSpotlightsIdRoute
  '/spotlights/$id/apply': typeof AppspotlightsSpotlightsIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(onboarding)/consent': typeof onboardingConsentRoute
  '/(onboarding)/onboarding': typeof onboardingOnboardingRoute
  '/(onboarding)/processing': typeof onboardingProcessingRoute
  '/(onboarding)/upload': typeof onboardingUploadRoute
  '/_app/industry': typeof AppIndustryRoute
  '/(landing)/': typeof landingIndexRoute
  '/(auth)/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/_app/(agents)/agents': typeof AppagentsAgentsRoute
  '/_app/(coach)/coach': typeof AppcoachCoachRoute
  '/_app/(dashboard)/home': typeof AppdashboardHomeRoute
  '/_app/(profile)/profile': typeof AppprofileProfileRoute
  '/_app/(profile)/wrapped': typeof AppprofileWrappedRoute
  '/_app/(settings)/settings': typeof AppsettingsSettingsRoute
  '/_app/(spending)/spending': typeof AppspendingSpendingRouteWithChildren
  '/_app/(spotlights)/spotlights': typeof AppspotlightsSpotlightsRouteWithChildren
  '/(auth)/accept-invite/': typeof authAcceptInviteIndexRoute
  '/_app/(spending)/spending/$category': typeof AppspendingSpendingCategoryRoute
  '/_app/(spotlights)/spotlights/$id': typeof AppspotlightsSpotlightsIdRoute
  '/_app/(spotlights)/spotlights/$id_/apply': typeof AppspotlightsSpotlightsIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/consent'
    | '/onboarding'
    | '/processing'
    | '/upload'
    | '/industry'
    | '/accept-invite/$token'
    | '/agents'
    | '/coach'
    | '/home'
    | '/profile'
    | '/wrapped'
    | '/settings'
    | '/spending'
    | '/spotlights'
    | '/accept-invite/'
    | '/spending/$category'
    | '/spotlights/$id'
    | '/spotlights/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/consent'
    | '/onboarding'
    | '/processing'
    | '/upload'
    | '/industry'
    | '/accept-invite/$token'
    | '/agents'
    | '/coach'
    | '/home'
    | '/profile'
    | '/wrapped'
    | '/settings'
    | '/spending'
    | '/spotlights'
    | '/accept-invite'
    | '/spending/$category'
    | '/spotlights/$id'
    | '/spotlights/$id/apply'
  id:
    | '__root__'
    | '/_app'
    | '/sitemap.xml'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/(onboarding)/consent'
    | '/(onboarding)/onboarding'
    | '/(onboarding)/processing'
    | '/(onboarding)/upload'
    | '/_app/industry'
    | '/(landing)/'
    | '/(auth)/accept-invite/$token'
    | '/_app/(agents)/agents'
    | '/_app/(coach)/coach'
    | '/_app/(dashboard)/home'
    | '/_app/(profile)/profile'
    | '/_app/(profile)/wrapped'
    | '/_app/(settings)/settings'
    | '/_app/(spending)/spending'
    | '/_app/(spotlights)/spotlights'
    | '/(auth)/accept-invite/'
    | '/_app/(spending)/spending/$category'
    | '/_app/(spotlights)/spotlights/$id'
    | '/_app/(spotlights)/spotlights/$id_/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  onboardingConsentRoute: typeof onboardingConsentRoute
  onboardingOnboardingRoute: typeof onboardingOnboardingRoute
  onboardingProcessingRoute: typeof onboardingProcessingRoute
  onboardingUploadRoute: typeof onboardingUploadRoute
  landingIndexRoute: typeof landingIndexRoute
  authAcceptInviteTokenRoute: typeof authAcceptInviteTokenRoute
  authAcceptInviteIndexRoute: typeof authAcceptInviteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/industry': {
      id: '/_app/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof AppIndustryRouteImport
      parentRoute: typeof AppRoute
    }
    '/(onboarding)/upload': {
      id: '/(onboarding)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof onboardingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/processing': {
      id: '/(onboarding)/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof onboardingProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/onboarding': {
      id: '/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof onboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/consent': {
      id: '/(onboarding)/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof onboardingConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invite/': {
      id: '/(auth)/accept-invite/'
      path: '/accept-invite'
      fullPath: '/accept-invite/'
      preLoaderRoute: typeof authAcceptInviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(spotlights)/spotlights': {
      id: '/_app/(spotlights)/spotlights'
      path: '/spotlights'
      fullPath: '/spotlights'
      preLoaderRoute: typeof AppspotlightsSpotlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(spending)/spending': {
      id: '/_app/(spending)/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AppspendingSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(settings)/settings': {
      id: '/_app/(settings)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppsettingsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(profile)/wrapped': {
      id: '/_app/(profile)/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AppprofileWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(profile)/profile': {
      id: '/_app/(profile)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppprofileProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(dashboard)/home': {
      id: '/_app/(dashboard)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppdashboardHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(coach)/coach': {
      id: '/_app/(coach)/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppcoachCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/(agents)/agents': {
      id: '/_app/(agents)/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppagentsAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/accept-invite/$token': {
      id: '/(auth)/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof authAcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/(spotlights)/spotlights/$id': {
      id: '/_app/(spotlights)/spotlights/$id'
      path: '/$id'
      fullPath: '/spotlights/$id'
      preLoaderRoute: typeof AppspotlightsSpotlightsIdRouteImport
      parentRoute: typeof AppspotlightsSpotlightsRoute
    }
    '/_app/(spending)/spending/$category': {
      id: '/_app/(spending)/spending/$category'
      path: '/$category'
      fullPath: '/spending/$category'
      preLoaderRoute: typeof AppspendingSpendingCategoryRouteImport
      parentRoute: typeof AppspendingSpendingRoute
    }
    '/_app/(spotlights)/spotlights/$id_/apply': {
      id: '/_app/(spotlights)/spotlights/$id_/apply'
      path: '/$id/apply'
      fullPath: '/spotlights/$id/apply'
      preLoaderRoute: typeof AppspotlightsSpotlightsIdApplyRouteImport
      parentRoute: typeof AppspotlightsSpotlightsRoute
    }
  }
}

interface AppspendingSpendingRouteChildren {
  AppspendingSpendingCategoryRoute: typeof AppspendingSpendingCategoryRoute
}

const AppspendingSpendingRouteChildren: AppspendingSpendingRouteChildren = {
  AppspendingSpendingCategoryRoute: AppspendingSpendingCategoryRoute,
}

const AppspendingSpendingRouteWithChildren =
  AppspendingSpendingRoute._addFileChildren(AppspendingSpendingRouteChildren)

interface AppspotlightsSpotlightsRouteChildren {
  AppspotlightsSpotlightsIdRoute: typeof AppspotlightsSpotlightsIdRoute
  AppspotlightsSpotlightsIdApplyRoute: typeof AppspotlightsSpotlightsIdApplyRoute
}

const AppspotlightsSpotlightsRouteChildren: AppspotlightsSpotlightsRouteChildren =
  {
    AppspotlightsSpotlightsIdRoute: AppspotlightsSpotlightsIdRoute,
    AppspotlightsSpotlightsIdApplyRoute: AppspotlightsSpotlightsIdApplyRoute,
  }

const AppspotlightsSpotlightsRouteWithChildren =
  AppspotlightsSpotlightsRoute._addFileChildren(
    AppspotlightsSpotlightsRouteChildren,
  )

interface AppRouteChildren {
  AppIndustryRoute: typeof AppIndustryRoute
  AppagentsAgentsRoute: typeof AppagentsAgentsRoute
  AppcoachCoachRoute: typeof AppcoachCoachRoute
  AppdashboardHomeRoute: typeof AppdashboardHomeRoute
  AppprofileProfileRoute: typeof AppprofileProfileRoute
  AppprofileWrappedRoute: typeof AppprofileWrappedRoute
  AppsettingsSettingsRoute: typeof AppsettingsSettingsRoute
  AppspendingSpendingRoute: typeof AppspendingSpendingRouteWithChildren
  AppspotlightsSpotlightsRoute: typeof AppspotlightsSpotlightsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndustryRoute: AppIndustryRoute,
  AppagentsAgentsRoute: AppagentsAgentsRoute,
  AppcoachCoachRoute: AppcoachCoachRoute,
  AppdashboardHomeRoute: AppdashboardHomeRoute,
  AppprofileProfileRoute: AppprofileProfileRoute,
  AppprofileWrappedRoute: AppprofileWrappedRoute,
  AppsettingsSettingsRoute: AppsettingsSettingsRoute,
  AppspendingSpendingRoute: AppspendingSpendingRouteWithChildren,
  AppspotlightsSpotlightsRoute: AppspotlightsSpotlightsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  onboardingConsentRoute: onboardingConsentRoute,
  onboardingOnboardingRoute: onboardingOnboardingRoute,
  onboardingProcessingRoute: onboardingProcessingRoute,
  onboardingUploadRoute: onboardingUploadRoute,
  landingIndexRoute: landingIndexRoute,
  authAcceptInviteTokenRoute: authAcceptInviteTokenRoute,
  authAcceptInviteIndexRoute: authAcceptInviteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
