/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWrappedRouteImport } from './routes/_app.wrapped'
import { Route as AppSpotlightsRouteImport } from './routes/_app.spotlights'
import { Route as AppSpendingRouteImport } from './routes/_app.spending'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppSpotlightsIdRouteImport } from './routes/_app.spotlights.$id'
import { Route as AppSpendingCategoryRouteImport } from './routes/_app.spending.$category'
import { Route as AppSpotlightsIdApplyRouteImport } from './routes/_app.spotlights.$id_.apply'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const AppSpotlightsRoute = AppSpotlightsRouteImport.update({
  id: '/spotlights',
  path: '/spotlights',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSpotlightsIdRoute = AppSpotlightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSpotlightsRoute,
} as any)
const AppSpendingCategoryRoute = AppSpendingCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AppSpendingRoute,
} as any)
const AppSpotlightsIdApplyRoute = AppSpotlightsIdApplyRouteImport.update({
  id: '/$id_/apply',
  path: '/$id/apply',
  getParentRoute: () => AppSpotlightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/agents': typeof AppAgentsRoute
  '/coach': typeof AppCoachRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/spending': typeof AppSpendingRouteWithChildren
  '/spotlights': typeof AppSpotlightsRouteWithChildren
  '/wrapped': typeof AppWrappedRoute
  '/spending/$category': typeof AppSpendingCategoryRoute
  '/spotlights/$id': typeof AppSpotlightsIdRoute
  '/spotlights/$id/apply': typeof AppSpotlightsIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/agents': typeof AppAgentsRoute
  '/coach': typeof AppCoachRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/spending': typeof AppSpendingRouteWithChildren
  '/spotlights': typeof AppSpotlightsRouteWithChildren
  '/wrapped': typeof AppWrappedRoute
  '/spending/$category': typeof AppSpendingCategoryRoute
  '/spotlights/$id': typeof AppSpotlightsIdRoute
  '/spotlights/$id/apply': typeof AppSpotlightsIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spending': typeof AppSpendingRouteWithChildren
  '/_app/spotlights': typeof AppSpotlightsRouteWithChildren
  '/_app/wrapped': typeof AppWrappedRoute
  '/_app/spending/$category': typeof AppSpendingCategoryRoute
  '/_app/spotlights/$id': typeof AppSpotlightsIdRoute
  '/_app/spotlights/$id_/apply': typeof AppSpotlightsIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/processing'
    | '/sitemap.xml'
    | '/upload'
    | '/agents'
    | '/coach'
    | '/home'
    | '/profile'
    | '/settings'
    | '/spending'
    | '/spotlights'
    | '/wrapped'
    | '/spending/$category'
    | '/spotlights/$id'
    | '/spotlights/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/login'
    | '/processing'
    | '/sitemap.xml'
    | '/upload'
    | '/agents'
    | '/coach'
    | '/home'
    | '/profile'
    | '/settings'
    | '/spending'
    | '/spotlights'
    | '/wrapped'
    | '/spending/$category'
    | '/spotlights/$id'
    | '/spotlights/$id/apply'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/consent'
    | '/login'
    | '/processing'
    | '/sitemap.xml'
    | '/upload'
    | '/_app/agents'
    | '/_app/coach'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/spending'
    | '/_app/spotlights'
    | '/_app/wrapped'
    | '/_app/spending/$category'
    | '/_app/spotlights/$id'
    | '/_app/spotlights/$id_/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wrapped': {
      id: '/_app/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spotlights': {
      id: '/_app/spotlights'
      path: '/spotlights'
      fullPath: '/spotlights'
      preLoaderRoute: typeof AppSpotlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spending': {
      id: '/_app/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spotlights/$id': {
      id: '/_app/spotlights/$id'
      path: '/$id'
      fullPath: '/spotlights/$id'
      preLoaderRoute: typeof AppSpotlightsIdRouteImport
      parentRoute: typeof AppSpotlightsRoute
    }
    '/_app/spending/$category': {
      id: '/_app/spending/$category'
      path: '/$category'
      fullPath: '/spending/$category'
      preLoaderRoute: typeof AppSpendingCategoryRouteImport
      parentRoute: typeof AppSpendingRoute
    }
    '/_app/spotlights/$id_/apply': {
      id: '/_app/spotlights/$id_/apply'
      path: '/$id/apply'
      fullPath: '/spotlights/$id/apply'
      preLoaderRoute: typeof AppSpotlightsIdApplyRouteImport
      parentRoute: typeof AppSpotlightsRoute
    }
  }
}

interface AppSpendingRouteChildren {
  AppSpendingCategoryRoute: typeof AppSpendingCategoryRoute
}

const AppSpendingRouteChildren: AppSpendingRouteChildren = {
  AppSpendingCategoryRoute: AppSpendingCategoryRoute,
}

const AppSpendingRouteWithChildren = AppSpendingRoute._addFileChildren(
  AppSpendingRouteChildren,
)

interface AppSpotlightsRouteChildren {
  AppSpotlightsIdRoute: typeof AppSpotlightsIdRoute
  AppSpotlightsIdApplyRoute: typeof AppSpotlightsIdApplyRoute
}

const AppSpotlightsRouteChildren: AppSpotlightsRouteChildren = {
  AppSpotlightsIdRoute: AppSpotlightsIdRoute,
  AppSpotlightsIdApplyRoute: AppSpotlightsIdApplyRoute,
}

const AppSpotlightsRouteWithChildren = AppSpotlightsRoute._addFileChildren(
  AppSpotlightsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppCoachRoute: typeof AppCoachRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpendingRoute: typeof AppSpendingRouteWithChildren
  AppSpotlightsRoute: typeof AppSpotlightsRouteWithChildren
  AppWrappedRoute: typeof AppWrappedRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppCoachRoute: AppCoachRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpendingRoute: AppSpendingRouteWithChildren,
  AppSpotlightsRoute: AppSpotlightsRouteWithChildren,
  AppWrappedRoute: AppWrappedRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
